---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: my-host-cleartext
spec:
  hostname: clear.35.237.242.24.nip.io
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
      additionalPort: 8080